package com.brandonkamga.lescracks.shared.bootstrap;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The starter catalogue of categories and tags, shared by the demo and production seeders so the
 * two environments can never drift apart. Order matters: LinkedHashMap keeps the catalogue
 * readable in the order it is declared here.
 */
final class Taxonomy {

    private Taxonomy() {
    }

    static Map<String, List<String>> data() {
        Map<String, List<String>> taxonomy = new LinkedHashMap<>();

        taxonomy.put("Backend", List.of("Java", "Python", "JavaScript", "TypeScript", "PHP", "C#", "Go", "Rust", "Node.js", "Spring Boot", "Django", "FastAPI", "Laravel", "Express.js", "NestJS", ".NET", "REST API", "GraphQL", "WebSocket", "Microservices", "ORM", "JPA", "Hibernate", "Middleware", "Routing", "Dependency Injection", "Server-side", "Authentication", "API Design", "Pagination", "Rate Limiting", "gRPC", "Event-driven", "Scheduling", "Web Server", "HTTP Server", "Socket Programming", "Graceful Shutdown", "Connection Handling", "Request Parsing", "Static Files", "Reverse Proxy", "Background Jobs", "Caching", "Webhooks", "Idempotency"));
        taxonomy.put("Frontend", List.of("HTML", "CSS", "JavaScript", "TypeScript", "React", "Angular", "Vue.js", "Svelte", "Next.js", "Nuxt.js", "Tailwind CSS", "Material UI", "DOM", "JSX", "Components", "Hooks", "State Management", "Redux", "Zustand", "Context API", "Forms", "Responsive Design", "Accessibility", "SPA", "SSR", "Web Components", "Vite", "Webpack", "CSS Grid", "Flexbox", "Animations", "PWA", "SEO technique", "Design System"));
        taxonomy.put("Programmation", List.of("Java", "Python", "C", "C++", "C#", "Go", "Rust", "PHP", "JavaScript", "TypeScript", "Variables", "Functions", "Loops", "Conditions", "Arrays", "Collections", "Exceptions", "Generics", "Interfaces", "Classes", "Objects", "Recursion", "Lambda", "Functional Programming", "OOP", "Memory Management", "Concurrency", "Regex", "Parsing", "Streams", "Debugging", "Refactoring", "Code Style", "Kotlin", "Ruby", "Swift", "Dart", "Zig", "Error Handling", "Pointers", "Dependency Injection", "Build Tags", "Testing"));
        taxonomy.put("Algorithmique", List.of("Algorithms", "Data Structures", "Arrays", "Linked List", "Stack", "Queue", "Hash Table", "HashMap", "Tree", "Binary Tree", "Binary Search Tree", "Heap", "Graph", "Trie", "Sorting", "Searching", "Binary Search", "Recursion", "Backtracking", "Dynamic Programming", "Greedy", "BFS", "DFS", "Big O", "Complexity", "Time Complexity", "Space Complexity", "Divide and Conquer", "Two Pointers", "Sliding Window", "Shortest Path", "Minimum Spanning Tree", "Topological Sort"));
        taxonomy.put("Base de données", List.of("SQL", "NoSQL", "PostgreSQL", "MySQL", "MariaDB", "SQLite", "Oracle", "MongoDB", "Redis", "Cassandra", "Tables", "Relations", "Primary Key", "Foreign Key", "Index", "Constraints", "Transactions", "ACID", "Joins", "Subqueries", "Views", "Stored Procedures", "Normalization", "Denormalization", "Database Design", "Query Optimization", "Migration", "Backup", "Replication", "Sharding", "Flyway", "Triggers", "JSONB"));
        taxonomy.put("DevOps", List.of("Docker", "Kubernetes", "CI/CD", "Jenkins", "GitHub Actions", "GitLab CI", "Ansible", "Terraform", "Linux", "Nginx", "Traefik", "Deployment", "Automation", "Infrastructure", "Containers", "Pipeline", "Build", "Release", "Monitoring", "Logging", "Scaling", "Infrastructure as Code", "Secrets Management", "Rollback", "Blue Green", "Canary", "GitOps", "ArgoCD", "Registry", "Compose", "Service Mesh"));
        taxonomy.put("Cloud", List.of("AWS", "Azure", "GCP", "EC2", "S3", "Lambda", "VPC", "IAM", "RDS", "DynamoDB", "CloudFront", "Route 53", "EKS", "ECS", "Azure VM", "Azure Blob Storage", "Azure Functions", "Google Compute Engine", "Cloud Run", "Cloud Storage", "Regions", "Availability Zones", "Serverless", "Virtual Machine", "Cloud Security", "Cloud Architecture", "Load Balancer", "Auto Scaling", "Managed Database", "Object Storage", "Billing", "Cost Optimization"));
        taxonomy.put("Linux", List.of("Ubuntu", "Debian", "Kali Linux", "Fedora", "CentOS", "Arch Linux", "Bash", "Shell", "Zsh", "Terminal", "SSH", "SCP", "Permissions", "Users", "Groups", "Processes", "Services", "Systemd", "Cron", "Package Management", "APT", "DNF", "File System", "Environment Variables", "Pipes", "Redirection", "grep", "awk", "sed", "vim", "chmod", "chown", "Networking", "Firewall", "Uptime", "Kernel", "File Descriptor", "System Calls", "strace", "lsof", "netstat", "Signals", "SIGTERM", "ulimit", "somaxconn", "procfs", "journalctl", "tmux"));
        taxonomy.put("Réseaux", List.of("TCP/IP", "HTTP", "HTTPS", "DNS", "DHCP", "FTP", "SSH", "SMTP", "IPv4", "IPv6", "MAC Address", "IP Address", "Subnetting", "CIDR", "Routing", "Switching", "NAT", "Firewall", "Proxy", "Reverse Proxy", "Load Balancer", "Port", "Socket", "OSI", "TCP", "UDP", "ICMP", "VLAN", "VPN", "Network Security", "Wireshark", "Bandwidth", "Latency", "HTTP/2", "TLS Handshake", "Berkeley Sockets", "Three-way Handshake", "Backlog", "SYN Queue", "Accept Queue", "TIME_WAIT", "SO_REUSEADDR", "Keep-Alive", "Loopback", "Ephemeral Port", "Nagle", "MTU", "QUIC", "HTTP/3", "netcat", "tcpdump", "ss", "curl"));
        taxonomy.put("Cybersécurité", List.of("OWASP", "XSS", "SQL Injection", "CSRF", "SSRF", "Authentication", "Authorization", "JWT", "OAuth2", "OpenID Connect", "HTTPS", "TLS", "Encryption", "Hashing", "Password Security", "MFA", "RBAC", "Vulnerability", "Pentest", "Network Security", "Web Security", "Linux Security", "Firewall", "Session Security", "Secure Coding", "CVE", "Zero Day", "Phishing", "Social Engineering", "Burp Suite", "Nmap", "Security Audit", "Incident Response"));
        taxonomy.put("Intelligence artificielle", List.of("AI", "Machine Learning", "Deep Learning", "LLM", "Generative AI", "NLP", "Computer Vision", "Neural Networks", "Transformers", "GPT", "Embeddings", "Prompt Engineering", "Fine-tuning", "Inference", "Training", "Classification", "Regression", "Clustering", "Recommendation", "TensorFlow", "PyTorch", "Scikit-learn", "RAG", "Vector Database", "Agents", "Evaluation", "Hallucination", "Tokenization", "Hugging Face", "Ollama"));
        taxonomy.put("Data Science", List.of("Python", "Pandas", "NumPy", "Matplotlib", "Jupyter", "Statistics", "Data Analysis", "Data Cleaning", "Data Visualization", "Exploratory Data Analysis", "Regression", "Classification", "Clustering", "Correlation", "Probability", "Dataset", "Feature Engineering", "Data Preprocessing", "Scikit-learn", "Seaborn", "Plotly", "Hypothesis Testing", "A/B Testing", "Time Series", "SQL", "Excel", "Power BI", "Data Pipeline", "ETL", "Dask"));
        taxonomy.put("Big Data", List.of("Hadoop", "Spark", "Kafka", "Flink", "Data Lake", "Data Warehouse", "ETL", "ELT", "Batch Processing", "Stream Processing", "Parquet", "Avro", "Hive", "Airflow", "dbt", "Snowflake", "Databricks", "Redshift", "BigQuery", "Data Mesh", "Partitioning", "Data Pipeline", "Orchestration", "Data Governance", "Data Quality"));
        taxonomy.put("Git", List.of("Git", "Repository", "Commit", "Branch", "Merge", "Rebase", "Clone", "Pull", "Push", "Fetch", "Stash", "Tag", "Cherry-pick", "Reset", "Revert", "Conflict", "HEAD", "Remote", "Git Config", "Git Log", "Git Diff", "Git Bisect", "Git Hooks", "Squash", "Amend", "Checkout", "Blame", "Worktree", "Submodules", "Signing", "Git Flow", "Conventional Commits"));
        taxonomy.put("GitHub", List.of("Repository", "Pull Request", "Issue", "Actions", "Workflow", "Runner", "Branch Protection", "Code Review", "Fork", "Release", "Tag", "GitHub Pages", "GitHub Projects", "GitHub Packages", "Secrets", "Environments", "Actions Marketplace", "CI/CD", "Dependabot", "CODEOWNERS", "Discussions", "Wiki", "Gist", "GitHub CLI", "Milestones", "Merge Queue", "Security Advisories", "Sponsors"));
        taxonomy.put("Architecture logicielle", List.of("Clean Architecture", "Hexagonal Architecture", "Layered Architecture", "MVC", "MVVM", "Microservices", "Monolith", "Modular Monolith", "DDD", "CQRS", "Event Sourcing", "SOLID", "Dependency Injection", "Separation of Concerns", "Design Principles", "Scalability", "Maintainability", "Coupling", "Cohesion", "Domain Model", "Bounded Context", "API Gateway", "Service Mesh", "Saga", "Outbox", "Anti-corruption Layer", "Ports and Adapters", "Vertical Slice"));
        taxonomy.put("Design Patterns", List.of("Singleton", "Factory", "Abstract Factory", "Builder", "Prototype", "Adapter", "Bridge", "Composite", "Decorator", "Facade", "Proxy", "Flyweight", "Strategy", "Observer", "Command", "State", "Template Method", "Iterator", "Mediator", "Memento", "Chain of Responsibility", "Visitor", "Repository Pattern", "Unit of Work", "Specification", "Dependency Injection", "Null Object", "Object Pool", "Circuit Breaker", "Retry"));
        taxonomy.put("Tests", List.of("Unit Testing", "Integration Testing", "End-to-End Testing", "Regression Testing", "JUnit", "Mockito", "Jest", "PyTest", "Cypress", "Playwright", "Testcontainers", "TDD", "BDD", "Mock", "Stub", "Fixture", "Assertion", "Test Coverage", "Test Case", "Test Suite", "Test Automation", "Smoke Testing", "Contract Testing", "Mutation Testing", "Property-based Testing", "Load Testing", "k6", "Postman", "Test Pyramid"));
        taxonomy.put("Java", List.of("Java", "JVM", "JDK", "JRE", "Maven", "Gradle", "Collections", "Streams", "Lambda", "Generics", "Threads", "Concurrency", "Multithreading", "Exception", "Interface", "Abstract Class", "Inheritance", "Polymorphism", "Encapsulation", "Reflection", "JDBC", "Records", "Sealed Classes", "Virtual Threads", "Optional", "Serialization", "Annotations", "Java 21", "Garbage Collector", "Classpath", "Modules", "Text Blocks", "Pattern Matching"));
        taxonomy.put("Spring", List.of("Spring Boot", "Spring MVC", "Spring Data", "Spring Security", "Spring Cloud", "Spring AI", "Spring Batch", "Spring Web", "Spring Validation", "Spring Actuator", "Dependency Injection", "IoC", "Bean", "REST Controller", "Repository", "Service", "Entity", "JPA", "Hibernate", "JWT", "OAuth2", "Configuration Properties", "Profiles", "AOP", "Scheduling", "Spring Events", "Flyway", "Testcontainers", "WebClient", "RestTemplate", "Spring DevTools"));
        taxonomy.put("Python", List.of("Python", "PIP", "Virtual Environment", "Venv", "Poetry", "Functions", "Decorators", "Generators", "Iterators", "List Comprehension", "Lambda", "Classes", "Dataclasses", "Exceptions", "Asyncio", "Multithreading", "Multiprocessing", "Type Hints", "PyTest", "FastAPI", "Django", "Flask", "Pandas", "Requests", "Slicing", "Context Managers", "F-strings", "Walrus Operator", "Pydantic", "Mypy", "Packaging", "UV"));
        taxonomy.put("Docker", List.of("Docker", "Dockerfile", "Image", "Container", "Docker Compose", "Volume", "Network", "Registry", "Docker Hub", "Build", "Run", "Exec", "Logs", "Port Mapping", "Environment Variables", "Multi-stage Build", "Healthcheck", "Container Security", "Docker CLI", "Entrypoint", "Layer Caching", "BuildKit", "Dockerignore", "Bind Mount", "Tmpfs", "Compose Profiles", "Docker Scout", "Distroless"));
        taxonomy.put("Kubernetes", List.of("Kubernetes", "Pod", "Deployment", "Service", "Namespace", "ConfigMap", "Secret", "Ingress", "Volume", "Persistent Volume", "StatefulSet", "DaemonSet", "ReplicaSet", "Job", "CronJob", "Helm", "Kubelet", "Kubectl", "Cluster", "Node", "Autoscaling", "HPA", "RBAC", "NetworkPolicy", "Probe", "Readiness", "Liveness", "Resource Limits", "Taints", "Affinity", "Operator", "Kustomize", "ArgoCD"));
        taxonomy.put("Infrastructure as Code", List.of("Terraform", "Ansible", "Pulumi", "CloudFormation", "Infrastructure", "Provisioning", "Automation", "Modules", "Variables", "State", "Backend", "Plan", "Apply", "Destroy", "Inventory", "Playbook", "Role", "Idempotency", "Configuration Management", "HCL", "Workspace", "Data Source", "Remote State", "Drift Detection", "Terragrunt", "OpenTofu", "Vault", "Import"));
        taxonomy.put("CI/CD", List.of("Continuous Integration", "Continuous Delivery", "Continuous Deployment", "GitHub Actions", "GitLab CI", "Jenkins", "Pipeline", "Workflow", "Runner", "Build", "Test", "Deploy", "Artifact", "Release", "Environment", "Secrets", "Deployment Strategy", "Rollback", "Blue Green Deployment", "Canary Deployment", "Matrix Builds", "Caching", "Quality Gate", "SonarQube", "Semantic Versioning", "Changelog", "Feature Flags", "Trunk-based Development"));
        taxonomy.put("Observabilité", List.of("Monitoring", "Logging", "Metrics", "Tracing", "Prometheus", "Grafana", "Loki", "OpenTelemetry", "Alerting", "Dashboard", "Health Check", "Application Metrics", "System Metrics", "Distributed Tracing", "Log Aggregation", "Performance Monitoring", "Error Tracking", "Sentry", "SLI", "SLO", "SLA", "Cardinality", "Exporters", "Node Exporter", "Blackbox", "Uptime", "Incident", "Runbook", "Golden Signals", "RED Method"));
        taxonomy.put("Développement mobile", List.of("Android", "Kotlin", "Java", "Flutter", "Dart", "React Native", "Swift", "iOS", "SwiftUI", "Jetpack Compose", "Android Studio", "Xcode", "Mobile UI", "Navigation", "State Management", "Push Notifications", "Local Storage", "SQLite", "Firebase", "REST API", "Play Store", "App Store", "Offline First", "Deep Links", "Permissions", "Gradle", "CocoaPods", "Fastlane", "Code Push", "Expo"));
        taxonomy.put("Développement web", List.of("Web", "HTTP", "HTTPS", "Browser", "URL", "Domain", "DNS", "Cookies", "Sessions", "CORS", "WebSocket", "REST", "API", "Authentication", "Authorization", "HTML", "CSS", "JavaScript", "Forms", "Upload", "Cache", "CDN", "Local Storage", "Service Worker", "Responsive", "Progressive Enhancement", "Web Vitals", "Rendering", "Hydration", "Edge", "Webhooks", "Rate Limiting", "HTTP Methods", "Status Codes", "Headers", "MIME Types", "Content Negotiation", "Request Line", "Keep-Alive", "Chunked Encoding", "HTTP/2", "HTTP/3"));
        taxonomy.put("UX/UI Design", List.of("UX", "UI", "Figma", "Wireframe", "Mockup", "Prototype", "Design System", "Typography", "Color Palette", "Spacing", "Grid", "Components", "Icons", "Illustration", "User Research", "Persona", "User Journey", "Usability", "Accessibility", "WCAG", "Contrast", "Information Architecture", "Micro-interactions", "Dark Mode", "Mobile First", "Design Tokens", "Handoff", "A/B Testing", "Heuristic Evaluation", "Affordance"));
        taxonomy.put("Gestion de projet", List.of("Agile", "Scrum", "Kanban", "Sprint", "Backlog", "User Story", "Epic", "Task", "Issue", "Roadmap", "Planning", "Estimation", "Stand-up", "Retrospective", "Product Backlog", "Sprint Planning", "Scrum Master", "Product Owner", "Velocity", "Burndown", "Definition of Done", "MVP", "Stakeholders", "Prioritization", "MoSCoW", "RICE", "OKR", "KPI", "Jira", "Linear", "Notion"));
        taxonomy.put("Qualité logicielle", List.of("Clean Code", "Code Review", "Refactoring", "SOLID", "Technical Debt", "Code Smell", "Maintainability", "Readability", "Documentation", "Naming", "Complexity", "Static Analysis", "SonarQube", "Linting", "Coding Standards", "Best Practices", "Pair Programming", "Code Coverage", "Duplication", "Cyclomatic Complexity", "Pre-commit Hooks", "EditorConfig", "Formatting", "Architecture Fitness", "Changelog", "Semantic Versioning"));
        taxonomy.put("Systèmes distribués", List.of("Distributed Systems", "Microservices", "Distributed Database", "Message Queue", "Kafka", "RabbitMQ", "Event-driven Architecture", "CAP Theorem", "Consistency", "Availability", "Partition Tolerance", "Replication", "Sharding", "Load Balancing", "Service Discovery", "Distributed Transactions", "Eventual Consistency", "Consensus", "Raft", "Paxos", "Leader Election", "Idempotency", "Saga", "Two-phase Commit", "Vector Clocks", "Gossip Protocol", "Backpressure"));
        taxonomy.put("Blockchain", List.of("Blockchain", "Bitcoin", "Ethereum", "Smart Contract", "Solidity", "Wallet", "Mining", "Proof of Work", "Proof of Stake", "Consensus", "NFT", "Token", "DeFi", "Web3", "DApp", "Gas", "Ledger", "Hash", "Cryptography", "Decentralization", "Layer 2", "EVM", "Metamask", "Stablecoin", "DAO"));
        taxonomy.put("IoT & Embarqué", List.of("IoT", "Embedded", "Raspberry Pi", "Arduino", "ESP32", "Microcontroller", "Sensor", "Actuator", "GPIO", "MQTT", "CoAP", "Firmware", "RTOS", "C", "C++", "Serial", "I2C", "SPI", "UART", "Edge Computing", "Telemetry", "Provisioning", "OTA Update", "Low Power", "Zigbee", "LoRaWAN", "Bluetooth", "Wear OS", "Home Assistant"));
        taxonomy.put("Carrières tech", List.of("CV", "Portfolio", "LinkedIn", "Entretien technique", "Entretien RH", "Coding Interview", "System Design Interview", "Take-home Test", "Salary Negotiation", "Freelance", "Remote Work", "Junior Developer", "Mid-level", "Senior", "Tech Lead", "CTO", "Open Source", "Side Project", "Mentoring", "Networking", "Certification", "English for Tech", "Impostor Syndrome", "Burnout", "Work-life Balance", "Recruiter", "Offer", "Onboarding"));

        return taxonomy;
    }
}
