package com.brandonkamga.lescracks.shared.bootstrap;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * The starter catalogue of categories and tags, shared by the demo and production seeders so the
 * two environments can never drift apart. Order matters: LinkedHashMap keeps the catalogue
 * readable in the order it is declared here.
 */
final class Taxonomy {

    private Taxonomy() {
    }

    static Map<String, List<String>> data() {
        Map<String, List<String>> taxonomy = new LinkedHashMap<>();

        taxonomy.put("Backend", List.of("Java", "Python", "JavaScript", "TypeScript", "PHP", "C#", "Go", "Rust", "Node.js", "Spring Boot", "Django", "FastAPI", "Laravel", "Express.js", "NestJS", ".NET", "REST API", "GraphQL", "WebSocket", "Microservices", "ORM", "JPA", "Hibernate", "Middleware", "Routing", "Dependency Injection", "Server-side", "Authentication", "API Design", "Pagination", "Rate Limiting", "gRPC", "Event-driven", "Scheduling", "Web Server", "HTTP Server", "Socket Programming", "Graceful Shutdown", "Connection Handling", "Request Parsing", "Static Files", "Reverse Proxy", "Background Jobs", "Caching", "Webhooks", "Idempotency"));
        taxonomy.put("Frontend", List.of("HTML", "CSS", "JavaScript", "TypeScript", "React", "Angular", "Vue.js", "Svelte", "Next.js", "Nuxt.js", "Tailwind CSS", "Material UI", "DOM", "JSX", "Components", "Hooks", "State Management", "Redux", "Zustand", "Context API", "Forms", "Responsive Design", "Accessibility", "SPA", "SSR", "Web Components", "Vite", "Webpack", "CSS Grid", "Flexbox", "Animations", "PWA", "SEO technique", "Design System"));
        taxonomy.put("Programmation", List.of("Java", "Python", "C", "C++", "C#", "Go", "Rust", "PHP", "JavaScript", "TypeScript", "Variables", "Functions", "Loops", "Conditions", "Arrays", "Collections", "Exceptions", "Generics", "Interfaces", "Classes", "Objects", "Recursion", "Lambda", "Functional Programming", "OOP", "Memory Management", "Concurrency", "Regex", "Parsing", "Streams", "Debugging", "Refactoring", "Code Style", "Kotlin", "Ruby", "Swift", "Dart", "Zig", "Error Handling", "Pointers", "Dependency Injection", "Build Tags", "Testing"));
        taxonomy.put("Algorithmique", List.of("Algorithms", "Data Structures", "Arrays", "Linked List", "Stack", "Queue", "Hash Table", "HashMap", "Tree", "Binary Tree", "Binary Search Tree", "Heap", "Graph", "Trie", "Sorting", "Searching", "Binary Search", "Recursion", "Backtracking", "Dynamic Programming", "Greedy", "BFS", "DFS", "Big O", "Complexity", "Time Complexity", "Space Complexity", "Divide and Conquer", "Two Pointers", "Sliding Window", "Shortest Path", "Minimum Spanning Tree", "Topological Sort"));
        taxonomy.put("Base de données", List.of("SQL", "NoSQL", "PostgreSQL", "MySQL", "MariaDB", "SQLite", "Oracle", "MongoDB", "Redis", "Cassandra", "Tables", "Relations", "Primary Key", "Foreign Key", "Index", "Constraints", "Transactions", "ACID", "Joins", "Subqueries", "Views", "Stored Procedures", "Normalization", "Denormalization", "Database Design", "Query Optimization", "Migration", "Backup", "Replication", "Sharding", "Flyway", "Triggers", "JSONB"));
        taxonomy.put("DevOps", List.of("Docker", "Kubernetes", "CI/CD", "Jenkins", "GitHub Actions", "GitLab CI", "Ansible", "Terraform", "Linux", "Nginx", "Traefik", "Deployment", "Automation", "Infrastructure", "Containers", "Pipeline", "Build", "Release", "Monitoring", "Logging", "Scaling", "Infrastructure as Code", "Secrets Management", "Rollback", "Blue Green", "Canary", "GitOps", "ArgoCD", "Registry", "Compose", "Service Mesh"));
        taxonomy.put("Cloud", List.of("AWS", "Azure", "GCP", "EC2", "S3", "Lambda", "VPC", "IAM", "RDS", "DynamoDB", "CloudFront", "Route 53", "EKS", "ECS", "Azure VM", "Azure Blob Storage", "Azure Functions", "Google Compute Engine", "Cloud Run", "Cloud Storage", "Regions", "Availability Zones", "Serverless", "Virtual Machine", "Cloud Security", "Cloud Architecture", "Load Balancer", "Auto Scaling", "Managed Database", "Object Storage", "Billing", "Cost Optimization"));
        taxonomy.put("Linux", List.of("Ubuntu", "Debian", "Kali Linux", "Fedora", "CentOS", "Arch Linux", "Bash", "Shell", "Zsh", "Terminal", "SSH", "SCP", "Permissions", "Users", "Groups", "Processes", "Services", "Systemd", "Cron", "Package Management", "APT", "DNF", "File System", "Environment Variables", "Pipes", "Redirection", "grep", "awk", "sed", "vim", "chmod", "chown", "Networking", "Firewall", "Uptime", "Kernel", "File Descriptor", "System Calls", "strace", "lsof", "netstat", "Signals", "SIGTERM", "ulimit", "somaxconn", "procfs", "journalctl", "tmux"));
        taxonomy.put("Réseaux", List.of("TCP/IP", "HTTP", "HTTPS", "DNS", "DHCP", "FTP", "SSH", "SMTP", "IPv4", "IPv6", "MAC Address", "IP Address", "Subnetting", "CIDR", "Routing", "Switching", "NAT", "Firewall", "Proxy", "Reverse Proxy", "Load Balancer", "Port", "Socket", "OSI", "TCP", "UDP", "ICMP", "VLAN", "VPN", "Network Security", "Wireshark", "Bandwidth", "Latency", "HTTP/2", "TLS Handshake", "Berkeley Sockets", "Three-way Handshake", "Backlog", "SYN Queue", "Accept Queue", "TIME_WAIT", "SO_REUSEADDR", "Keep-Alive", "Loopback", "Ephemeral Port", "Nagle", "MTU", "QUIC", "HTTP/3", "netcat", "tcpdump", "ss", "curl"));
        taxonomy.put("Cybersécurité", List.of("OWASP", "XSS", "SQL Injection", "CSRF", "SSRF", "Authentication", "Authorization", "JWT", "OAuth2", "OpenID Connect", "HTTPS", "TLS", "Encryption", "Hashing", "Password Security", "MFA", "RBAC", "Vulnerability", "Pentest", "Network Security", "Web Security", "Linux Security", "Firewall", "Session Security", "Secure Coding", "CVE", "Zero Day", "Phishing", "Social Engineering", "Burp Suite", "Nmap", "Security Audit", "Incident Response"));
        taxonomy.put("Intelligence artificielle", List.of("AI", "Machine Learning", "Deep Learning", "LLM", "Generative AI", "NLP", "Computer Vision", "Neural Networks", "Transformers", "GPT", "Embeddings", "Prompt Engineering", "Fine-tuning", "Inference", "Training", "Classification", "Regression", "Clustering", "Recommendation", "TensorFlow", "PyTorch", "Scikit-learn", "RAG", "Vector Database", "Agents", "Evaluation", "Hallucination", "Tokenization", "Hugging Face", "Ollama"));
        taxonomy.put("Data Science", List.of("Python", "Pandas", "NumPy", "Matplotlib", "Jupyter", "Statistics", "Data Analysis", "Data Cleaning", "Data Visualization", "Exploratory Data Analysis", "Regression", "Classification", "Clustering", "Correlation", "Probability", "Dataset", "Feature Engineering", "Data Preprocessing", "Scikit-learn", "Seaborn", "Plotly", "Hypothesis Testing", "A/B Testing", "Time Series", "SQL", "Excel", "Power BI", "Data Pipeline", "ETL", "Dask"));
        taxonomy.put("Big Data", List.of("Hadoop", "Spark", "Kafka", "Flink", "Data Lake", "Data Warehouse", "ETL", "ELT", "Batch Processing", "Stream Processing", "Parquet", "Avro", "Hive", "Airflow", "dbt", "Snowflake", "Databricks", "Redshift", "BigQuery", "Data Mesh", "Partitioning", "Data Pipeline", "Orchestration", "Data Governance", "Data Quality"));
        taxonomy.put("Git", List.of("Git", "Repository", "Commit", "Branch", "Merge", "Rebase", "Clone", "Pull", "Push", "Fetch", "Stash", "Tag", "Cherry-pick", "Reset", "Revert", "Conflict", "HEAD", "Remote", "Git Config", "Git Log", "Git Diff", "Git Bisect", "Git Hooks", "Squash", "Amend", "Checkout", "Blame", "Worktree", "Submodules", "Signing", "Git Flow", "Conventional Commits"));
        taxonomy.put("GitHub", List.of("Repository", "Pull Request", "Issue", "Actions", "Workflow", "Runner", "Branch Protection", "Code Review", "Fork", "Release", "Tag", "GitHub Pages", "GitHub Projects", "GitHub Packages", "Secrets", "Environments", "Actions Marketplace", "CI/CD", "Dependabot", "CODEOWNERS", "Discussions", "Wiki", "Gist", "GitHub CLI", "Milestones", "Merge Queue", "Security Advisories", "Sponsors"));
        taxonomy.put("Architecture logicielle", List.of("Clean Architecture", "Hexagonal Architecture", "Layered Architecture", "MVC", "MVVM", "Microservices", "Monolith", "Modular Monolith", "DDD", "CQRS", "Event Sourcing", "SOLID", "Dependency Injection", "Separation of Concerns", "Design Principles", "Scalability", "Maintainability", "Coupling", "Cohesion", "Domain Model", "Bounded Context", "API Gateway", "Service Mesh", "Saga", "Outbox", "Anti-corruption Layer", "Ports and Adapters", "Vertical Slice"));
        taxonomy.put("Design Patterns", List.of("Singleton", "Factory", "Abstract Factory", "Builder", "Prototype", "Adapter", "Bridge", "Composite", "Decorator", "Facade", "Proxy", "Flyweight", "Strategy", "Observer", "Command", "State", "Template Method", "Iterator", "Mediator", "Memento", "Chain of Responsibility", "Visitor", "Repository Pattern", "Unit of Work", "Specification", "Dependency Injection", "Null Object", "Object Pool", "Circuit Breaker", "Retry"));
        taxonomy.put("Tests", List.of("Unit Testing", "Integration Testing", "End-to-End Testing", "Regression Testing", "JUnit", "Mockito", "Jest", "PyTest", "Cypress", "Playwright", "Testcontainers", "TDD", "BDD", "Mock", "Stub", "Fixture", "Assertion", "Test Coverage", "Test Case", "Test Suite", "Test Automation", "Smoke Testing", "Contract Testing", "Mutation Testing", "Property-based Testing", "Load Testing", "k6", "Postman", "Test Pyramid"));
        taxonomy.put("Java", List.of("Java", "JVM", "JDK", "JRE", "Maven", "Gradle", "Collections", "Streams", "Lambda", "Generics", "Threads", "Concurrency", "Multithreading", "Exception", "Interface", "Abstract Class", "Inheritance", "Polymorphism", "Encapsulation", "Reflection", "JDBC", "Records", "Sealed Classes", "Virtual Threads", "Optional", "Serialization", "Annotations", "Java 21", "Garbage Collector", "Classpath", "Modules", "Text Blocks", "Pattern Matching"));
        taxonomy.put("Spring", List.of("Spring Boot", "Spring MVC", "Spring Data", "Spring Security", "Spring Cloud", "Spring AI", "Spring Batch", "Spring Web", "Spring Validation", "Spring Actuator", "Dependency Injection", "IoC", "Bean", "REST Controller", "Repository", "Service", "Entity", "JPA", "Hibernate", "JWT", "OAuth2", "Configuration Properties", "Profiles", "AOP", "Scheduling", "Spring Events", "Flyway", "Testcontainers", "WebClient", "RestTemplate", "Spring DevTools"));
        taxonomy.put("Python", List.of("Python", "PIP", "Virtual Environment", "Venv", "Poetry", "Functions", "Decorators", "Generators", "Iterators", "List Comprehension", "Lambda", "Classes", "Dataclasses", "Exceptions", "Asyncio", "Multithreading", "Multiprocessing", "Type Hints", "PyTest", "FastAPI", "Django", "Flask", "Pandas", "Requests", "Slicing", "Context Managers", "F-strings", "Walrus Operator", "Pydantic", "Mypy", "Packaging", "UV"));
        taxonomy.put("Docker", List.of("Docker", "Dockerfile", "Image", "Container", "Docker Compose", "Volume", "Network", "Registry", "Docker Hub", "Build", "Run", "Exec", "Logs", "Port Mapping", "Environment Variables", "Multi-stage Build", "Healthcheck", "Container Security", "Docker CLI", "Entrypoint", "Layer Caching", "BuildKit", "Dockerignore", "Bind Mount", "Tmpfs", "Compose Profiles", "Docker Scout", "Distroless"));
        taxonomy.put("Kubernetes", List.of("Kubernetes", "Pod", "Deployment", "Service", "Namespace", "ConfigMap", "Secret", "Ingress", "Volume", "Persistent Volume", "StatefulSet", "DaemonSet", "ReplicaSet", "Job", "CronJob", "Helm", "Kubelet", "Kubectl", "Cluster", "Node", "Autoscaling", "HPA", "RBAC", "NetworkPolicy", "Probe", "Readiness", "Liveness", "Resource Limits", "Taints", "Affinity", "Operator", "Kustomize", "ArgoCD"));
        taxonomy.put("Infrastructure as Code", List.of("Terraform", "Ansible", "Pulumi", "CloudFormation", "Infrastructure", "Provisioning", "Automation", "Modules", "Variables", "State", "Backend", "Plan", "Apply", "Destroy", "Inventory", "Playbook", "Role", "Idempotency", "Configuration Management", "HCL", "Workspace", "Data Source", "Remote State", "Drift Detection", "Terragrunt", "OpenTofu", "Vault", "Import"));
        taxonomy.put("CI/CD", List.of("Continuous Integration", "Continuous Delivery", "Continuous Deployment", "GitHub Actions", "GitLab CI", "Jenkins", "Pipeline", "Workflow", "Runner", "Build", "Test", "Deploy", "Artifact", "Release", "Environment", "Secrets", "Deployment Strategy", "Rollback", "Blue Green Deployment", "Canary Deployment", "Matrix Builds", "Caching", "Quality Gate", "SonarQube", "Semantic Versioning", "Changelog", "Feature Flags", "Trunk-based Development"));
        taxonomy.put("Observabilité", List.of("Monitoring", "Logging", "Metrics", "Tracing", "Prometheus", "Grafana", "Loki", "OpenTelemetry", "Alerting", "Dashboard", "Health Check", "Application Metrics", "System Metrics", "Distributed Tracing", "Log Aggregation", "Performance Monitoring", "Error Tracking", "Sentry", "SLI", "SLO", "SLA", "Cardinality", "Exporters", "Node Exporter", "Blackbox", "Uptime", "Incident", "Runbook", "Golden Signals", "RED Method"));
        taxonomy.put("Développement mobile", List.of("Android", "Kotlin", "Java", "Flutter", "Dart", "React Native", "Swift", "iOS", "SwiftUI", "Jetpack Compose", "Android Studio", "Xcode", "Mobile UI", "Navigation", "State Management", "Push Notifications", "Local Storage", "SQLite", "Firebase", "REST API", "Play Store", "App Store", "Offline First", "Deep Links", "Permissions", "Gradle", "CocoaPods", "Fastlane", "Code Push", "Expo"));
        taxonomy.put("Développement web", List.of("Web", "HTTP", "HTTPS", "Browser", "URL", "Domain", "DNS", "Cookies", "Sessions", "CORS", "WebSocket", "REST", "API", "Authentication", "Authorization", "HTML", "CSS", "JavaScript", "Forms", "Upload", "Cache", "CDN", "Local Storage", "Service Worker", "Responsive", "Progressive Enhancement", "Web Vitals", "Rendering", "Hydration", "Edge", "Webhooks", "Rate Limiting", "HTTP Methods", "Status Codes", "Headers", "MIME Types", "Content Negotiation", "Request Line", "Keep-Alive", "Chunked Encoding", "HTTP/2", "HTTP/3"));
        taxonomy.put("UX/UI Design", List.of("UX", "UI", "Figma", "Wireframe", "Mockup", "Prototype", "Design System", "Typography", "Color Palette", "Spacing", "Grid", "Components", "Icons", "Illustration", "User Research", "Persona", "User Journey", "Usability", "Accessibility", "WCAG", "Contrast", "Information Architecture", "Micro-interactions", "Dark Mode", "Mobile First", "Design Tokens", "Handoff", "A/B Testing", "Heuristic Evaluation", "Affordance"));
        taxonomy.put("Gestion de projet", List.of("Agile", "Scrum", "Kanban", "Sprint", "Backlog", "User Story", "Epic", "Task", "Issue", "Roadmap", "Planning", "Estimation", "Stand-up", "Retrospective", "Product Backlog", "Sprint Planning", "Scrum Master", "Product Owner", "Velocity", "Burndown", "Definition of Done", "MVP", "Stakeholders", "Prioritization", "MoSCoW", "RICE", "OKR", "KPI", "Jira", "Linear", "Notion"));
        taxonomy.put("Qualité logicielle", List.of("Clean Code", "Code Review", "Refactoring", "SOLID", "Technical Debt", "Code Smell", "Maintainability", "Readability", "Documentation", "Naming", "Complexity", "Static Analysis", "SonarQube", "Linting", "Coding Standards", "Best Practices", "Pair Programming", "Code Coverage", "Duplication", "Cyclomatic Complexity", "Pre-commit Hooks", "EditorConfig", "Formatting", "Architecture Fitness", "Changelog", "Semantic Versioning"));
        taxonomy.put("Systèmes distribués", List.of("Distributed Systems", "Microservices", "Distributed Database", "Message Queue", "Kafka", "RabbitMQ", "Event-driven Architecture", "CAP Theorem", "Consistency", "Availability", "Partition Tolerance", "Replication", "Sharding", "Load Balancing", "Service Discovery", "Distributed Transactions", "Eventual Consistency", "Consensus", "Raft", "Paxos", "Leader Election", "Idempotency", "Saga", "Two-phase Commit", "Vector Clocks", "Gossip Protocol", "Backpressure"));
        taxonomy.put("Blockchain", List.of("Blockchain", "Bitcoin", "Ethereum", "Smart Contract", "Solidity", "Wallet", "Mining", "Proof of Work", "Proof of Stake", "Consensus", "NFT", "Token", "DeFi", "Web3", "DApp", "Gas", "Ledger", "Hash", "Cryptography", "Decentralization", "Layer 2", "EVM", "Metamask", "Stablecoin", "DAO"));
        taxonomy.put("IoT & Embarqué", List.of("IoT", "Embedded", "Raspberry Pi", "Arduino", "ESP32", "Microcontroller", "Sensor", "Actuator", "GPIO", "MQTT", "CoAP", "Firmware", "RTOS", "C", "C++", "Serial", "I2C", "SPI", "UART", "Edge Computing", "Telemetry", "Provisioning", "OTA Update", "Low Power", "Zigbee", "LoRaWAN", "Bluetooth", "Wear OS", "Home Assistant"));
        taxonomy.put("Carrières tech", List.of("CV", "Portfolio", "LinkedIn", "Entretien technique", "Entretien RH", "Coding Interview", "System Design Interview", "Take-home Test", "Salary Negotiation", "Freelance", "Remote Work", "Junior Developer", "Mid-level", "Senior", "Tech Lead", "CTO", "Open Source", "Side Project", "Mentoring", "Networking", "Certification", "English for Tech", "Impostor Syndrome", "Burnout", "Work-life Balance", "Recruiter", "Offer", "Onboarding"));
        taxonomy.put("Go", List.of("Go", "Go Modules", "Goroutines", "Channels", "Select", "Context", "sync", "WaitGroup", "Mutex", "Interfaces", "Structs", "Methods", "Pointers", "Slices", "Maps", "Error Handling", "Errors Wrapping", "Generics", "Defer", "Panic and Recover", "net", "net/http", "syscall", "io.Reader", "io.Writer", "Testing", "Table-driven Tests", "Benchmarks", "Race Detector", "go vet", "gofmt", "Build Tags", "Cross-compilation", "pprof", "Gin", "Echo", "Fiber", "Cobra", "gRPC"));
        taxonomy.put("Rust", List.of("Rust", "Cargo", "Crates", "Ownership", "Borrowing", "Lifetimes", "Traits", "Generics", "Enums", "Pattern Matching", "Option", "Result", "Error Handling", "Macros", "Smart Pointers", "Box", "Rc", "Arc", "Unsafe", "Async", "Tokio", "Actix", "Axum", "Serde", "Clippy", "Rustfmt", "Iterators", "Closures", "FFI", "Embedded Rust", "WebAssembly"));
        taxonomy.put("JavaScript", List.of("JavaScript", "ES6+", "Variables", "Scope", "Closures", "Hoisting", "this", "Prototypes", "Classes", "Promises", "Async/Await", "Event Loop", "Callbacks", "Modules", "Destructuring", "Spread", "Arrow Functions", "Array Methods", "Map and Set", "Fetch API", "DOM", "Events", "JSON", "Regex", "Error Handling", "Iterators", "Generators", "Proxy", "Web Workers", "Debugging"));
        taxonomy.put("TypeScript", List.of("TypeScript", "Types", "Interfaces", "Type Aliases", "Union Types", "Intersection Types", "Generics", "Enums", "Type Guards", "Narrowing", "Utility Types", "Mapped Types", "Conditional Types", "Template Literal Types", "Decorators", "tsconfig", "Strict Mode", "Declaration Files", "Type Inference", "Zod", "Discriminated Unions", "Satisfies", "Module Resolution", "Monorepo"));
        taxonomy.put("Node.js", List.of("Node.js", "npm", "pnpm", "Yarn", "Bun", "Deno", "Express.js", "Fastify", "NestJS", "Koa", "Event Loop", "Streams", "Buffers", "File System", "Child Processes", "Worker Threads", "Cluster", "Environment Variables", "Middleware", "REST API", "WebSocket", "Socket.IO", "Prisma", "TypeORM", "Sequelize", "Mongoose", "Jest", "Vitest", "PM2", "Package Publishing"));
        taxonomy.put("C & C++", List.of("C", "C++", "Pointers", "Memory Management", "malloc", "Stack and Heap", "Structs", "Header Files", "Preprocessor", "Makefile", "CMake", "GCC", "Clang", "GDB", "Valgrind", "Undefined Behavior", "Segmentation Fault", "Buffer Overflow", "STL", "Templates", "RAII", "Smart Pointers", "Move Semantics", "Modern C++", "Classes", "Inheritance", "Operator Overloading", "POSIX", "Sockets", "Linking"));
        taxonomy.put("PHP", List.of("PHP", "Composer", "Laravel", "Symfony", "Eloquent", "Doctrine", "Blade", "Twig", "PSR", "PHPUnit", "Pest", "Namespaces", "Traits", "Interfaces", "Sessions", "Cookies", "PDO", "Middleware", "Artisan", "Livewire", "WordPress", "REST API", "Queues", "PHP 8", "Attributes"));
        taxonomy.put("C# & .NET", List.of("C#", ".NET", "ASP.NET Core", "Entity Framework", "LINQ", "Minimal API", "Blazor", "MAUI", "NuGet", "Dependency Injection", "Middleware", "Async/Await", "Tasks", "Delegates", "Events", "Generics", "Records", "Pattern Matching", "xUnit", "NUnit", "SignalR", "Azure", "Unity", "Visual Studio", "Rider"));
        taxonomy.put("Kotlin", List.of("Kotlin", "Coroutines", "Flow", "Null Safety", "Data Classes", "Sealed Classes", "Extension Functions", "Lambdas", "Collections", "Gradle", "Kotlin Multiplatform", "Jetpack Compose", "Ktor", "Spring Boot", "Android", "DSL", "Delegation", "Generics", "Kotest", "MockK"));
        taxonomy.put("Ruby", List.of("Ruby", "Ruby on Rails", "Gems", "Bundler", "Blocks", "Procs", "Lambdas", "Modules", "Mixins", "Metaprogramming", "ActiveRecord", "Migrations", "RSpec", "Minitest", "Rake", "Sinatra", "Hotwire", "Turbo", "Sidekiq", "Rubocop"));
        taxonomy.put("Projets from scratch", List.of("From Scratch", "Kross", "Serveur web", "Serveur HTTP", "Shell", "Interpréteur", "Compilateur", "Base de données", "Clé-valeur", "Redis", "Git", "Conteneur", "Load Balancer", "Reverse Proxy", "Serveur DNS", "Client HTTP", "Chat en temps réel", "Moteur de recherche", "Système de fichiers", "Émulateur", "Moteur de jeu", "Éditeur de texte", "Langage de programmation", "Blockchain", "Bot", "File de messages", "Rate Limiter", "URL Shortener", "Template Engine", "Pas à pas"));
        taxonomy.put("Programmation système", List.of("System Calls", "File Descriptor", "Sockets", "Berkeley Sockets", "POSIX", "libc", "Processes", "fork", "exec", "Threads", "Signals", "Pipes", "IPC", "Shared Memory", "Memory Mapping", "mmap", "epoll", "kqueue", "io_uring", "Non-blocking I/O", "Event Loop", "Daemons", "strace", "ELF", "Linker", "Endianness", "Buffers", "Zero-copy"));
        taxonomy.put("Systèmes d'exploitation", List.of("Kernel", "User Space", "Kernel Space", "Processes", "Threads", "Scheduling", "Context Switch", "Virtual Memory", "Paging", "Memory Allocation", "File Systems", "Inodes", "Drivers", "Interrupts", "System Calls", "Boot Process", "BIOS", "UEFI", "Bootloader", "Deadlock", "Semaphores", "Mutex", "Virtualization", "Hypervisor", "Namespaces", "cgroups", "Windows", "macOS", "Linux", "FreeBSD"));
        taxonomy.put("Concurrence & parallélisme", List.of("Concurrency", "Parallelism", "Threads", "Thread Pool", "Goroutines", "Async/Await", "Coroutines", "Event Loop", "Actors", "Futures", "Promises", "Race Condition", "Deadlock", "Livelock", "Starvation", "Mutex", "Semaphore", "Atomic Operations", "Lock-free", "Memory Model", "Channels", "Producer-Consumer", "Fan-out Fan-in", "Backpressure", "Virtual Threads", "Work Stealing", "Reactive Programming", "Data Race"));
        taxonomy.put("Performance", List.of("Performance", "Profiling", "Benchmarking", "Latency", "Throughput", "Caching", "CDN", "Lazy Loading", "Memory Leaks", "Garbage Collection", "CPU Profiling", "Flame Graphs", "Load Testing", "Query Optimization", "Indexes", "Connection Pooling", "Compression", "Web Vitals", "Bundle Size", "Code Splitting", "Big O", "Horizontal Scaling", "Vertical Scaling", "Capacity Planning", "N+1 Queries", "Tail Latency"));
        taxonomy.put("Compilateurs & interpréteurs", List.of("Compiler", "Interpreter", "Lexer", "Tokenizer", "Parser", "AST", "Grammar", "BNF", "Recursive Descent", "Pratt Parser", "Semantic Analysis", "Type Checking", "Intermediate Representation", "Bytecode", "Virtual Machine", "JIT", "LLVM", "Code Generation", "Optimization", "Garbage Collector", "REPL", "Transpiler", "Babel", "Regex Engine", "DSL"));
        taxonomy.put("WebAssembly", List.of("WebAssembly", "WASM", "WASI", "Emscripten", "wasm-pack", "Rust", "Go", "AssemblyScript", "Wasmtime", "Wasmer", "Component Model", "Edge Computing", "Plugins", "Sandboxing", "JavaScript Interop", "Performance"));
        taxonomy.put("Conception d'API", List.of("REST", "GraphQL", "gRPC", "tRPC", "OpenAPI", "Swagger", "API First", "Resource Modeling", "HTTP Methods", "Status Codes", "Versioning", "Pagination", "Filtering", "Sorting", "Rate Limiting", "Idempotency", "HATEOAS", "Webhooks", "Error Format", "Problem Details", "Authentication", "API Keys", "OAuth2", "CORS", "API Gateway", "Contract Testing", "Backward Compatibility", "Deprecation", "SDK", "Documentation"));
        taxonomy.put("Messagerie & streaming", List.of("Message Queue", "Message Broker", "Pub/Sub", "Kafka", "RabbitMQ", "NATS", "Redis Streams", "Amazon SQS", "Amazon SNS", "Google Pub/Sub", "Pulsar", "Topics", "Partitions", "Consumer Groups", "Offsets", "Dead Letter Queue", "Retry", "At-least-once", "Exactly-once", "Ordering", "Event Sourcing", "CDC", "Debezium", "Outbox", "Schema Registry", "Stream Processing", "Kafka Streams", "Backpressure"));
        taxonomy.put("Moteurs de recherche", List.of("Search Engine", "Full-text Search", "Elasticsearch", "OpenSearch", "Meilisearch", "Typesense", "Solr", "Lucene", "Inverted Index", "Tokenization", "Stemming", "Analyzers", "Relevance", "BM25", "TF-IDF", "Faceting", "Autocomplete", "Fuzzy Search", "Synonyms", "Vector Search", "Hybrid Search", "PostgreSQL Full-text", "Indexing Pipeline", "Kibana"));
        taxonomy.put("SRE", List.of("SRE", "Reliability", "SLI", "SLO", "SLA", "Error Budget", "Toil", "On-call", "Incident Management", "Postmortem", "Blameless", "Runbook", "Chaos Engineering", "Disaster Recovery", "Backup", "High Availability", "Failover", "Redundancy", "Capacity Planning", "Alerting", "Observability", "Graceful Degradation", "Circuit Breaker", "Health Checks", "Zero Downtime"));
        taxonomy.put("MLOps", List.of("MLOps", "Model Training", "Model Serving", "Model Registry", "Feature Store", "Experiment Tracking", "MLflow", "Kubeflow", "DVC", "Weights & Biases", "Data Versioning", "Model Monitoring", "Data Drift", "Model Drift", "Batch Inference", "Real-time Inference", "GPU", "ONNX", "Triton", "BentoML", "Vertex AI", "SageMaker", "LLMOps", "Evaluation", "A/B Testing"));
        taxonomy.put("Cryptographie", List.of("Cryptography", "Symmetric Encryption", "Asymmetric Encryption", "AES", "RSA", "Elliptic Curves", "Diffie-Hellman", "Hash Functions", "SHA-256", "HMAC", "Digital Signatures", "Certificates", "PKI", "X.509", "TLS", "Let's Encrypt", "Key Management", "Salting", "bcrypt", "Argon2", "Random Numbers", "End-to-end Encryption", "Zero-knowledge Proof", "Post-quantum", "Base64"));
        taxonomy.put("Identité & accès", List.of("Identity", "Authentication", "Authorization", "SSO", "OAuth2", "OpenID Connect", "SAML", "JWT", "Sessions", "Cookies", "Refresh Token", "PKCE", "MFA", "Passkeys", "WebAuthn", "RBAC", "ABAC", "Keycloak", "Auth0", "Okta", "Firebase Auth", "LDAP", "Active Directory", "Least Privilege", "Social Login", "Password Reset"));
        taxonomy.put("Cache", List.of("Cache", "Redis", "Memcached", "In-memory Cache", "Distributed Cache", "HTTP Cache", "Cache-Control", "ETag", "CDN", "Cache Invalidation", "TTL", "Eviction", "LRU", "LFU", "Cache-aside", "Write-through", "Write-behind", "Read-through", "Cache Stampede", "Warm-up", "Hit Ratio", "Varnish", "Spring Cache", "Caffeine"));

        return taxonomy;
    }
}
