-- V1 — Baseline of the schema as it already exists in production.
-- Fresh databases replay this; production is marked as already-at-V1 via
-- spring.flyway.baseline-on-migrate, so this file never runs there.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: application_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT application_types_name_check CHECK (((name)::text = ANY ((ARRAY['apply'::character varying, 'register'::character varying, 'participate'::character varying, 'accompagnement_360'::character varying, 'formation_classique'::character varying])::text[])))
);


--
-- Name: application_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.applications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    motivation_text text,
    status character varying(255) NOT NULL,
    technical_level character varying(255),
    application_type_id bigint NOT NULL,
    event_id bigint,
    user_id bigint NOT NULL,
    age integer,
    email_address character varying(255),
    full_name character varying(255),
    whatsapp_number character varying(255),
    CONSTRAINT applications_status_check CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying])::text[])))
);


--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contributor_projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contributor_projects (
    contributor_id bigint NOT NULL,
    project_name character varying(255)
);


--
-- Name: contributors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contributors (
    id bigint NOT NULL,
    description text,
    display_order integer NOT NULL,
    github_url character varying(255),
    linkedin_url character varying(255),
    name character varying(255) NOT NULL,
    photo_url character varying(255),
    twitter_url character varying(255),
    visible boolean NOT NULL,
    website_url character varying(255)
);


--
-- Name: contributors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contributors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contributors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_statuses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_statuses (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT event_statuses_name_check CHECK (((name)::text = ANY ((ARRAY['open'::character varying, 'closed'::character varying, 'upcoming'::character varying])::text[])))
);


--
-- Name: event_statuses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_statuses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_statuses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_tags (
    event_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: event_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: event_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    application_required boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    event_date timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    event_status_id bigint NOT NULL,
    event_type_id bigint NOT NULL,
    cover_image_url character varying(255),
    end_date timestamp(6) without time zone,
    location character varying(255)
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: image_assets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.image_assets (
    id bigint NOT NULL,
    file_size bigint,
    image_type character varying(255) NOT NULL,
    mime_type character varying(255),
    url character varying(255) NOT NULL,
    user_id bigint,
    CONSTRAINT image_assets_image_type_check CHECK (((image_type)::text = ANY ((ARRAY['video_preview'::character varying, 'document_preview'::character varying, 'user_profile'::character varying])::text[])))
);


--
-- Name: image_assets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.image_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learners; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learners (
    id bigint NOT NULL,
    bio text,
    cohort character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    email character varying(255),
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    linkedin_url character varying(255),
    photo_url character varying(255),
    portfolio_url character varying(255),
    showcased boolean NOT NULL,
    slug character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    visible boolean NOT NULL,
    user_id bigint,
    CONSTRAINT learners_status_check CHECK (((status)::text = ANY ((ARRAY['EN_COURS'::character varying, 'TERMINE_AVEC_CERTIFICAT'::character varying, 'TERMINE_SANS_CERTIFICAT'::character varying])::text[])))
);


--
-- Name: learners_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: open_source_projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.open_source_projects (
    id bigint NOT NULL,
    description text,
    featured boolean NOT NULL,
    featured_order integer NOT NULL,
    forks integer NOT NULL,
    language character varying(255),
    logo_url character varying(255),
    name character varying(255) NOT NULL,
    repo_url character varying(255),
    stars integer NOT NULL,
    tech_stack character varying(255),
    visible boolean NOT NULL
);


--
-- Name: open_source_projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.open_source_projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.open_source_projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: premium_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.premium_requests (
    id bigint NOT NULL,
    country character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message character varying(1000),
    status character varying(255) NOT NULL,
    whatsapp_number character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    contact_email character varying(255),
    CONSTRAINT premium_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONTACTED'::character varying, 'PAID'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: premium_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.premium_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.premium_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    id bigint NOT NULL,
    description character varying(200),
    provider_name character varying(50) NOT NULL,
    CONSTRAINT providers_provider_name_check CHECK (((provider_name)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying, 'GITHUB'::character varying])::text[])))
);


--
-- Name: providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_metadata (
    id bigint NOT NULL,
    duration_seconds integer,
    file_size bigint,
    mime_type character varying(255),
    original_file_name character varying(255),
    storage_path character varying(255),
    resource_id bigint NOT NULL
);


--
-- Name: resource_metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource_metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_tags (
    resource_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: resource_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource_types (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT resource_types_name_check CHECK (((name)::text = ANY ((ARRAY['video'::character varying, 'document'::character varying])::text[])))
);


--
-- Name: resource_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resources (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    download_count bigint NOT NULL,
    is_downloadable boolean NOT NULL,
    is_premium boolean NOT NULL,
    preview_image_url character varying(255),
    source_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    url character varying(255) NOT NULL,
    view_count bigint NOT NULL,
    category_id bigint NOT NULL,
    resource_type_id bigint NOT NULL,
    slug character varying(255),
    CONSTRAINT resources_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['EXTERNAL'::character varying, 'UPLOADED'::character varying])::text[])))
);


--
-- Name: resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    category_id bigint NOT NULL
);


--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_tags (
    user_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    country character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    password character varying(255),
    phone character varying(255),
    premium_activated_at timestamp(6) without time zone,
    provider_user_id character varying(100),
    username character varying(255) NOT NULL,
    provider_id bigint NOT NULL,
    role_id bigint NOT NULL,
    picture_url character varying(512),
    premium_contact_email character varying(255),
    premium_expires_at timestamp(6) without time zone,
    verification_token character varying(100),
    email_verified boolean DEFAULT false NOT NULL,
    verification_token_expires_at timestamp(6) without time zone
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_types application_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_types
    ADD CONSTRAINT application_types_pkey PRIMARY KEY (id);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: contributors contributors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributors
    ADD CONSTRAINT contributors_pkey PRIMARY KEY (id);


--
-- Name: event_statuses event_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_statuses
    ADD CONSTRAINT event_statuses_pkey PRIMARY KEY (id);


--
-- Name: event_tags event_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT event_tags_pkey PRIMARY KEY (event_id, tag_id);


--
-- Name: event_types event_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_types
    ADD CONSTRAINT event_types_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: image_assets image_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_assets
    ADD CONSTRAINT image_assets_pkey PRIMARY KEY (id);


--
-- Name: learners learners_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learners
    ADD CONSTRAINT learners_pkey PRIMARY KEY (id);


--
-- Name: open_source_projects open_source_projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.open_source_projects
    ADD CONSTRAINT open_source_projects_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: premium_requests premium_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.premium_requests
    ADD CONSTRAINT premium_requests_pkey PRIMARY KEY (id);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- Name: resource_metadata resource_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_metadata
    ADD CONSTRAINT resource_metadata_pkey PRIMARY KEY (id);


--
-- Name: resource_tags resource_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tags
    ADD CONSTRAINT resource_tags_pkey PRIMARY KEY (resource_id, tag_id);


--
-- Name: resource_types resource_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_types
    ADD CONSTRAINT resource_types_pkey PRIMARY KEY (id);


--
-- Name: resources resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: resource_metadata uk3ntu38m3bprkelbaatg423lg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_metadata
    ADD CONSTRAINT uk3ntu38m3bprkelbaatg423lg UNIQUE (resource_id);


--
-- Name: resource_types uk6657495gxa15kc39an4jahc89; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_types
    ADD CONSTRAINT uk6657495gxa15kc39an4jahc89 UNIQUE (name);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: image_assets uk7o0tl7dyoeqgd00sui0p0eyh9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_assets
    ADD CONSTRAINT uk7o0tl7dyoeqgd00sui0p0eyh9 UNIQUE (user_id);


--
-- Name: learners uka8h4lmkaobaypsm8k1gywstae; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learners
    ADD CONSTRAINT uka8h4lmkaobaypsm8k1gywstae UNIQUE (slug);


--
-- Name: application_types ukc19ohm4xa01xwd2yqn9hgvvrt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_types
    ADD CONSTRAINT ukc19ohm4xa01xwd2yqn9hgvvrt UNIQUE (name);


--
-- Name: learners uki3r97iixtlqnv4gdycckfr57r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learners
    ADD CONSTRAINT uki3r97iixtlqnv4gdycckfr57r UNIQUE (user_id);


--
-- Name: event_statuses uki7y5aj814lqq292vbrj3js7r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_statuses
    ADD CONSTRAINT uki7y5aj814lqq292vbrj3js7r UNIQUE (name);


--
-- Name: resources ukmv2jm8etnirwg2ql46j34smkt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT ukmv2jm8etnirwg2ql46j34smkt UNIQUE (slug);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: providers uks0oh4d6p6mwmfmfcwxhwysmfn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT uks0oh4d6p6mwmfmfcwxhwysmfn UNIQUE (provider_name);


--
-- Name: categories ukt8o6pivur7nn124jehx7cygw5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name);


--
-- Name: user_tags user_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tags
    ADD CONSTRAINT user_tags_pkey PRIMARY KEY (user_id, tag_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: resource_tags fk1iba1kh2ulcqdhelp7oxn315w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tags
    ADD CONSTRAINT fk1iba1kh2ulcqdhelp7oxn315w FOREIGN KEY (resource_id) REFERENCES public.resources(id);


--
-- Name: applications fk1s1jbq8240ud2378ixe82or6d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fk1s1jbq8240ud2378ixe82or6d FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: events fk2198du56mf1aoaxrdlw3du288; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk2198du56mf1aoaxrdlw3du288 FOREIGN KEY (event_type_id) REFERENCES public.event_types(id);


--
-- Name: events fk2fr6bmov203s0p1p86kkj56j2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk2fr6bmov203s0p1p86kkj56j2 FOREIGN KEY (event_status_id) REFERENCES public.event_statuses(id);


--
-- Name: resources fk4d6jo4pc9qn6bsp24l8ii8evf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT fk4d6jo4pc9qn6bsp24l8ii8evf FOREIGN KEY (resource_type_id) REFERENCES public.resource_types(id);


--
-- Name: learners fk8i9112p7o8e24pqvyl39omln5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learners
    ADD CONSTRAINT fk8i9112p7o8e24pqvyl39omln5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: tags fkaq0uu400dxvsd0nkj9lpny908; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT fkaq0uu400dxvsd0nkj9lpny908 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: user_tags fkdylhtw3qjb2nj40xp50b0p495; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tags
    ADD CONSTRAINT fkdylhtw3qjb2nj40xp50b0p495 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: resource_tags fkebvwissjka7b9huq6i5jkhqwn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_tags
    ADD CONSTRAINT fkebvwissjka7b9huq6i5jkhqwn FOREIGN KEY (tag_id) REFERENCES public.tags(id);


--
-- Name: image_assets fkexuiptc10lj5tb9j57n4sm3pb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.image_assets
    ADD CONSTRAINT fkexuiptc10lj5tb9j57n4sm3pb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: applications fkfsfqljedcla632u568jl5qf3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkfsfqljedcla632u568jl5qf3w FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: contributor_projects fkgm7j2dotc67u5bt2mm5jb6m8a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributor_projects
    ADD CONSTRAINT fkgm7j2dotc67u5bt2mm5jb6m8a FOREIGN KEY (contributor_id) REFERENCES public.contributors(id);


--
-- Name: resource_metadata fkhy6tbhotgwoqe2bgi0bkp662w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource_metadata
    ADD CONSTRAINT fkhy6tbhotgwoqe2bgi0bkp662w FOREIGN KEY (resource_id) REFERENCES public.resources(id);


--
-- Name: user_tags fkioatd2q4dvvsb5k6al6ge8au4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_tags
    ADD CONSTRAINT fkioatd2q4dvvsb5k6al6ge8au4 FOREIGN KEY (tag_id) REFERENCES public.tags(id);


--
-- Name: event_tags fkiwoyitw224ykom58m5xnoa9y6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT fkiwoyitw224ykom58m5xnoa9y6 FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: applications fkk069fb24x53qvkoc4tnfxk5vn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkk069fb24x53qvkoc4tnfxk5vn FOREIGN KEY (application_type_id) REFERENCES public.application_types(id);


--
-- Name: resources fkkqsnjjtshc9v5lqp03fw9lw48; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT fkkqsnjjtshc9v5lqp03fw9lw48 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: users fkm2svscf5jy4774ew0k77puql; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkm2svscf5jy4774ew0k77puql FOREIGN KEY (provider_id) REFERENCES public.providers(id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: premium_requests fkt000epv6hpydkfi5d16owjmwn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.premium_requests
    ADD CONSTRAINT fkt000epv6hpydkfi5d16owjmwn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: event_tags fkt07xql63t6125c0wjk4j0lmqa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_tags
    ADD CONSTRAINT fkt07xql63t6125c0wjk4j0lmqa FOREIGN KEY (tag_id) REFERENCES public.tags(id);


--
-- PostgreSQL database dump complete
--


